version: '3'
services:
  server:
    image: postgrest/postgrest
    container_name: pgrest_server
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: app_user # In production this role should not be the same as the one used for the connection
    depends_on:
      - db

  db:
    image: postgres
    container_name: pgrest_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data" # Persist the data

  swagger:
    image: swaggerapi/swagger-ui
    container_name: pgrest_swagger
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost/api

  nginx:
    image: nginx:alpine
    container_name: pgrest_nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - "./pgrest_nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - server
